config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :properties do
    resources :bookings, only: [:create, :new]
    resources :reviews, only: [:create, :new]
  end

  resources :bookings, only: [:index, :show, :edit, :update, :destroy]
  resources :reviews, only: [:index, :show, :edit, :update, :destroy]

  namespace :api do
    namespace :v1 do
      resources :properties, only: [:index, :show]
    end
  end

  root to: 'properties#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :property

  validates :start_date, :end_date, :total_price, presence: true
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews

  validates :title, :description, :price, :location, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :property


  validates :rating, :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable



  has_many :properties
  has_many :bookings
  has_many :reviews
end

app/controllers/api/v1/bookings_controller.rb
class Api::V1::BookingsController < ApplicationController
end

app/controllers/api/v1/properties_controller.rb
class Api::V1::PropertiesController < ApplicationController
  def index
    @properties = Property.all
    render json: @properties
  end

  def show
    @property = Property.find(params[:id])
    render json: @property
  end
end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def index
    @bookings = current_user.bookings
  end

  def show
  end

  def new
    @property = Property.find(params[:property_id])
    @booking = @property.bookings.build
  end

  def create
    @property = Property.find(params[:property_id])
    @booking = @property.bookings.build(booking_params)
    @booking.user = current_user
    @booking.total_price = @property.price * (booking_params[:end_date].to_date - booking_params[:start_date].to_date).to_i

    if @booking.save
      redirect_to @booking, notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @booking.update(booking_params)
      redirect_to @booking, notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_url, notice: 'Booking was successfully destroyed.'
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price)
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  def index
    @properties = Property.all
  end

  def show
  end

  def new
    @property = current_user.properties.build
  end

  def create
    @property = current_user.properties.build(property_params)
    if @property.save
      redirect_to @property, notice: 'Property was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @property.update(property_params)
      redirect_to @property, notice: 'Property was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @property.destroy
    redirect_to properties_url, notice: 'Property was successfully destroyed.'
  end

  private

  def set_property
    @property = Property.find(params[:id])
  end

  def property_params
    params.require(:property).permit(:title, :description, :price, :location)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  def index
    @reviews = current_user.reviews
  end

  def show
  end

  def new
    @property = Property.find(params[:property_id])
    @review = @property.reviews.build
  end

  def create
    @property = Property.find(params[:property_id])
    @review = @property.reviews.build(review_params)
    @review.user = current_user

    if @review.save
      redirect_to @review, notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to @review, notice: 'Review was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to reviews_url, notice: 'Review was successfully destroyed.'
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:rating, :comment)
  end

end

app/helpers/api/v1/bookings_helper.rb
module Api::V1::BookingsHelper
end

app/helpers/api/v1/properties_helper.rb
module Api::V1::PropertiesHelper
end

app/helpers/api/v1/reviews_helper.rb
module Api::V1::ReviewsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookings/edit.html.erb
<h1>Edit Booking</h1>

<%= form_with(model: @booking, local: true) do |form| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_field :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_field :end_date %>
  </div>

  <div class="actions">
    <%= form.submit "Update Booking" %>
  </div>
<% end %>

<%= link_to 'Back', booking_path(@booking) %>

app/views/bookings/index.html.erb
<h1>My Bookings</h1>

<% if @bookings.any? %>
  <ul>
    <% @bookings.each do |booking| %>
      <li>
        <%= link_to "Booking ##{booking.id}", booking_path(booking) %> -
        Property: <%= booking.property.title %> -
        Total Price: <%= number_to_currency(booking.total_price) %>
        <p>From: <%= booking.start_date %> To: <%= booking.end_date %></p>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>You have no bookings.</p>
<% end %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= form_with(model: [@property, @booking], local: true) do |form| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_field :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_field :end_date %>
  </div>

  <div class="actions">
    <%= form.submit "Book Now" %>
  </div>
<% end %>

<%= link_to 'Back', property_path(@property) %>

app/views/bookings/show.html.erb
<h1>Booking Details</h1>

<p>
  <strong>Property:</strong> <%= link_to @booking.property.title, property_path(@booking.property) %>
</p>

<p>
  <strong>Start Date:</strong> <%= @booking.start_date %>
</p>

<p>
  <strong>End Date:</strong> <%= @booking.end_date %>
</p>

<p>
  <strong>Total Price:</strong> <%= number_to_currency(@booking.total_price) %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbClone1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <%= link_to 'Airbnb Clone', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'My Properties', properties_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container mt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/properties/_form.html.erb
<%= simple_form_for(@property) do |f| %>
  <div class="form-group">
    <%= f.input :title, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :description, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :price, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.input :location, input_html: { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<div class="container mt-5">
  <h1>Edit Property</h1>

  <%= render 'form' %>

  <%= link_to 'Back', properties_path, class: 'btn btn-secondary' %>
</div>

app/views/properties/index.html.erb
<h1>Properties</h1>

<%= link_to 'New Property', new_property_path %>

<div class="container mt-5">
  <h1 class="mb-4">Available Properties</h1>
  <div class="row">
    <% @properties.each do |property| %>
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <img src="https://via.placeholder.com/350x150" class="card-img-top" alt="<%= property.title %>">
          <div class="card-body">
            <h5 class="card-title"><%= link_to property.title, property_path(property) %></h5>
            <p class="card-text"><%= truncate(property.description, length: 100) %></p>
            <p class="card-text"><strong>Price:</strong> <%= number_to_currency(property.price) %></p>
            <p class="card-text"><strong>Location:</strong> <%= property.location %></p>
            <%= link_to 'View Details', property_path(property), class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/properties/new.html.erb
<div class="container mt-5">
  <h1>New Property</h1>

  <%= render 'form' %>

  <%= link_to 'Back', properties_path, class: 'btn btn-secondary' %>
</div>

app/views/properties/show.html.erb
<div class="container mt-5">
  <h1><%= @property.title %></h1>
  <div class="row">
    <div class="col-md-8">
      <img src="https://via.placeholder.com/750x300" class="img-fluid" alt="<%= @property.title %>">
      <p class="mt-4"><%= @property.description %></p>
    </div>
    <div class="col-md-4">
      <h3>Booking Details</h3>
      <p><strong>Price per Night:</strong> <%= number_to_currency(@property.price) %></p>
      <p><strong>Location:</strong> <%= @property.location %></p>
      <%= link_to 'Edit', edit_property_path(@property), class: 'btn btn-secondary' %> |
      <%= link_to 'Back', properties_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= form_with(model: @review, local: true) do |form| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit "Update Review" %>
  </div>
<% end %>

<%= link_to 'Back', review_path(@review) %>

app/views/reviews/index.html.erb
<h1>My Reviews</h1>

<% if @reviews.any? %>
  <ul>
    <% @reviews.each do |review| %>
      <li>
        <%= link_to "Review ##{review.id}", review_path(review) %> -
        Property: <%= review.property.title %> -
        Rating: <%= review.rating %>
        <p><%= review.comment %></p>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>You have no reviews.</p>
<% end %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= form_with(model: [@property, @review], local: true) do |form| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit "Submit Review" %>
  </div>
<% end %>

<%= link_to 'Back', property_path(@property) %>

app/views/reviews/show.html.erb
<h1>Review Details</h1>

<p>
  <strong>Property:</strong> <%= link_to @review.property.title, property_path(@review.property) %>
</p>

<p>
  <strong>Rating:</strong> <%= @review.rating %>
</p>

<p>
  <strong>Comment:</strong> <%= @review.comment %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>